### ISSUE TITLE
Two changeText are defined in runElmApp.js.

### ISSUE THREAD

**Issue by derbuihan** [gaaamii/nekobito#177]
https://github.com/gaaamii/nekobito/blob/9b84d1e4a7fb1e4ac1838f223fb171fc47932690/src/runElmApp.js#L70-L73

https://github.com/gaaamii/nekobito/blob/9b84d1e4a7fb1e4ac1838f223fb171fc47932690/src/runElmApp.js#L87-L90

**Comment by gaaamii** [comment]
Thank you for reporting. I will fix it in a few days.
