### ISSUE TITLE
Shortcut behavior in split mode

### ISSUE THREAD

**Issue by baibai25** [gaaamii/nekobito#188]
nekobito愛用しております。
ショートカットの挙動について、恐らく意図した動作をしていなそうなため質問をさせてください。

### 発生事象
- Layout Splitの状態において、markdownを記述する際に、"e"または"p"キーを押すとLayout Singleに切り替わってしまう
- Layout Single Editの状態において、markdownを記述する際に、"p"キーを押すとPreviewモードに切り替わってしまう
- Layout Single Previewの状態において、markdownを記述する際に、"e"キーを押すとEditモードに切り替わってしまう

### 発生環境
- OS: Mac, Linux
- Browser: Chrome
- URL: https://nekobito.netlify.app/

### 原因
- 恐らく #183

タイピング中に特定のキーを押すとモードが切り替わってしまうため、一度ご確認をお願い致します。
（本当であれば修正のPR送りたいところですが、インターンから数年、書き方の記憶がなく。。。
意図した挙動であればCloseしちゃってください！）

**Comment by baibai25** [comment]
![Peek 2022-11-12 02-42](https://user-images.githubusercontent.com/32119295/201398627-5e79ee5c-7af6-4110-89fe-da5200896021.gif)

**Comment by gaaamii** [comment]
丁寧にissue報告ありがとうございます。
こちらのバグ、実はマージ後すぐに気づいてまして、これから修正しますのでしばしお待ちを 🙏🏻 

そしていまでもnekobito使っていただけてるとのことで、ありがとうございます。今後はメインのブランチに入れるのはもうちょっと慎重に確認してからにしようと思います（最近は、どうせ自分しか使ってないかなと思って雑になっていました... 💦 ）

**Comment by gaaamii** [comment]
@baibai25 修正しましたのでお試しください 🙏🏻 その他も気になるところあればいつでもissue報告お待ちしてます 🙌🏻

**Comment by gaaamii** [comment]
触ってみて気づいたんですが、`Control + e`もカーソル位置の移動で使いたいことがあるのでショートカットキーに割り当ててしまってはまずいですね。ちょっと別案を考えてみます... 💦

**Comment by gaaamii** [comment]
こちらで修正しました https://github.com/gaaamii/nekobito/pull/192

Singleのときの切り替えにはControlキーを2回入力するようにしました。また、Splitモードのときは何も起きないようにしました 🙏🏻

**Comment by baibai25** [comment]
@gaaamii 
ご対応ありがとうございました！使い倒します:bow:
