### ISSUE TITLE
Does Nekobito support Markdown Tables ?

### ISSUE THREAD

**Issue by hanahiroAze** [gaaamii/nekobito#6]
## problem

when I write a table like this in markdown,
```
|  a | b  | c  | d  | e  |
|---|---|---|---|---|
| aa  | bb  | cc  | dd  | ee  |
```

Nekobito seems to show it as law text 
<img width="424" alt="スクリーンショット 2020-01-04 14 22 11" src="https://user-images.githubusercontent.com/9178166/71760227-9c2cb280-2efd-11ea-89ce-c1d42789ffbd.png">

**Comment by gaaamii** [comment]
Thank you for a feedback.

Nekobito uses a markdown parser which doesn't support tables right now. But I think it should be supported.

**Comment by gaaamii** [comment]
@hanahiroAze
I'm sorry to have kept you waiting for a long time. I finally supported it!
I noticed that elm-explorations/markdown library supports GitHub flavored markdown tables, so I just used [these options](https://package.elm-lang.org/packages/elm-explorations/markdown/latest/Markdown#Options).
